# Runs repository unit tests.
name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**translations.yml'
      - '.python-version'
      - 'requirements*.txt'
      - 'translations/*.py'
  pull_request:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - '**translations.yml'
      - '.python-version'
      - 'requirements*.txt'
      - 'translations/*.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

  # Disable permissions for all available scopes by default.
  # Any needed permissions should be configured individually for each job.
permissions: {}

jobs:
  # Runs the pytest unit tests for the translation script.
  translation-unit-tests:
    name: 'Run translation script tests'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
        with:
          cache: 'pip'
          python-version-file: '.python-version'
          pip-install: '-r requirements.txt'

      - name: Run unit tests
        run: pytest -v
